# Generated by Django 3.0.7 on 2020-07-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=1000)),
                ('id', models.IntegerField(default='', primary_key='id', serialize=False)),
                ('cover_image', models.ImageField(upload_to='upasanaapp/images')),
            ],
        ),
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=1000)),
                ('id', models.IntegerField(default='', primary_key='id', serialize=False)),
                ('file', models.FileField(null=True, upload_to='upasanaapp/videos/', verbose_name='')),
            ],
        ),
    ]
