# Generated by Django 3.0.7 on 2020-07-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upasanaapp', '0002_videodata_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='ytlink',
            field=models.CharField(default='', max_length=100),
        ),
    ]
