# Generated by Django 3.0.7 on 2020-08-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upasanaapp', '0003_videodata_ytlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmhouse_detail',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=1000)),
                ('mobile_no', models.IntegerField(default='')),
                ('email', models.EmailField(max_length=254)),
                ('f_id', models.IntegerField(default='', primary_key='id', serialize=False)),
                ('cover_image', models.ImageField(upload_to='upasanaapp/images')),
            ],
        ),
    ]
